/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.FundInventoryRole;
import Business.Enterprise.FundCompany;
import Business.FundProduct.FundProduct;
import Business.FundProduct.FundProductDirectory;
import Business.Organization.FundCompanyTradeOraganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Coco
 */
public class FundTradeWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form FundTradeWorkArea
     */
     public static final String UPDATE_Fund = "updateFund";
    
    JPanel userProcessContainer;
    UserAccount account;
    FundCompanyTradeOraganization organization;
    FundCompany enterprise;
    FundProductDirectory fundProductDirectory;
     public FundTradeWorkArea(JPanel upc, UserAccount ua,FundCompanyTradeOraganization fcto,FundCompany fc) {
         initComponents();
         userProcessContainer=upc;
        account=ua;
        organization=fcto;
        enterprise=fc;
        this.fundProductDirectory = fc.getFundProductDirectory();
         userProcessContainer.addPropertyChangeListener(UPDATE_Fund, new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent pce) {
                populateTable();
                System.out.println("manage Change() called!!!!!!!!!!!!!!!!!!!");
            }
            
        });
      
        lblEnterprise.setText(enterprise.getName());
        
        if(fundProductDirectory != null)
            populateTable();
    }
 public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblManageFunds.getModel();

        model.setRowCount(0);

        for (FundProduct fp : fundProductDirectory.getFundProductDirectory()) {
            Object[] row = new Object[9];
            row[0] = fp;
            row[1] = fp.getId();
            row[2] = fp.getDescription();
            row[3] = fp.getFundType();
            row[4] = fp.getPurchaseDate();
            row[5] = fp.getRedemptionDate();
            row[6] = fp.getPurchasePrice();
            row[7] = fp.getRedemptionPrice();
            row[8] = fp.getQuantity();
            
            model.addRow(row);
        }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageFunds = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Manage Fund Catalog");

        tblManageFunds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Description", "Type", "Purchase Date", "Redemption Date", "Purchase Price", "Redemption Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageFunds);

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel2.setText("Enterprise:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnDelete)
                        .addGap(56, 56, 56)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblEnterprise))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnAdd))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
          int selectedRow = tblManageFunds.getSelectedRow();
        if (selectedRow >= 0) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the Fund Product?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                FundProduct fp = (FundProduct) tblManageFunds.getValueAt(selectedRow, 0);
                fundProductDirectory.deleteFundProduct(fp);
                populateTable();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select one row!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
          int selectedRow = tblManageFunds.getSelectedRow();
        if (selectedRow >= 0) {
        
                FundProduct fp = (FundProduct) tblManageFunds.getValueAt(selectedRow, 0);
            
                   UpdateFundProductJPanel ufpjp= new UpdateFundProductJPanel(userProcessContainer,enterprise,fp);
        userProcessContainer.add("UpdateFundProductJPanel", ufpjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
                
        } else {
            JOptionPane.showMessageDialog(null, "Please select one row!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    
        
        
     
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
          AddFundProductJPanel afpjp= new AddFundProductJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("AddFundProductJPanel", afpjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JTable tblManageFunds;
    // End of variables declaration//GEN-END:variables
}
