/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.PlatformTradeRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FundCompany;
import Business.Enterprise.Platform;
import Business.FundProduct.FundProduct;
import Business.FundProduct.FundProductDirectory;
import Business.Network.Network;
import Business.Organization.PlatformTradeOrganization;
import Business.UserAccount.UserAccount;
import Util.Validation;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yangyun
 */
public class PlatformTradeWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form PlatformTradeWorkArea
     */
    JPanel userProcessContainer;
    UserAccount account;
    PlatformTradeOrganization organization;
    Platform enterprise;
    FundProductDirectory allDirectory;
    EcoSystem business;
    ArrayList<FundProduct> list;
    int cou = 0;
    ArrayList<FundProduct> result;
    
    public PlatformTradeWorkArea(JPanel userProcessContainer, UserAccount account, PlatformTradeOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = (Platform)enterprise;
        this.organization = organization;
        this.business = business;
        list = new ArrayList<>();
        lblEnterprise.setText(enterprise.getName());
        
        allDirectory = new FundProductDirectory();
        for(Network n : business.getNetworkList()){
            for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof FundCompany){
                    FundCompany fc =(FundCompany) e;
                    if(fc.getFundProductDirectory() != null){
                        for(FundProduct f : fc.getFundProductDirectory().getFundProductDirectory()){
                            //System.out.println("3");
                            allDirectory.plusFundProduct(f);
                        }
                    }
                }
            }
        }
        for(FundProduct.FundType t : FundProduct.FundType.values()){
            cmbType.addItem(t);
        }
        
        for(Network n : business.getNetworkList()){
            for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof FundCompany){
                    cmbCompany.addItem(e);
                }
            }
        }
        cmbType.setSelectedItem(null);
        cmbCompany.setSelectedItem(null);
        
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblManageFunds.getModel();

        model.setRowCount(0);

        for (FundProduct fp : allDirectory.getFundProductDirectory()) {
            Object[] row = new Object[5];
            row[0] = fp;
            row[1] = fp.getQuantity();
            row[2] = fp.getPurchasePrice();
            row[3] = fp.getRedemptionPrice();
            row[4] = fp.getFundType();
            model.addRow(row);
        }
 }
    
    private void populateTable2() {
        DefaultTableModel model = (DefaultTableModel) tblManageFunds.getModel();

        model.setRowCount(0);

        for (FundProduct fp : result) {
            Object[] row = new Object[5];
            row[0] = fp;
            row[1] = fp.getQuantity();
            row[2] = fp.getPurchasePrice();
            row[3] = fp.getRedemptionPrice();
            row[4] = fp.getFundType();
            model.addRow(row);
        }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageFunds = new javax.swing.JTable();
        btnPurchase = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnCompare = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btn2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPP1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPP2 = new javax.swing.JTextField();
        btn3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtRP1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRP2 = new javax.swing.JTextField();
        btn4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cmbCompany = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Fund Trade");

        jLabel2.setText("Enterprise:");

        tblManageFunds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity", "Purchase Price", "Redemption Price", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageFunds);

        btnPurchase.setBackground(new java.awt.Color(255, 255, 255));
        btnPurchase.setText("Make Purchase");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add to Compare List");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCompare.setBackground(new java.awt.Color(255, 255, 255));
        btnCompare.setText("Compare");
        btnCompare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompareActionPerformed(evt);
            }
        });

        btnDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnDetails.setText("Look Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(255, 255, 255));
        btn1.setText("Search1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Fund Name:");

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        btn2.setText("Search2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Purchase Price:");

        jLabel5.setText("to");

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        btn3.setText("Search3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Redemption Price:");

        jLabel7.setText("to");

        btn4.setBackground(new java.awt.Color(255, 255, 255));
        btn4.setText("Search4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Fund Type:");

        cmbType.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Show All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(255, 255, 255));
        btn5.setText("Search5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Fund Company:");

        cmbCompany.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(183, 183, 183)
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCompare, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btn2)
                                                .addComponent(btn1))
                                            .addGap(49, 49, 49)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPP1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPP2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtName)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtRP1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRP2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbCompany, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblEnterprise))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompare)
                    .addComponent(btnAdd)
                    .addComponent(btnDetails)
                    .addComponent(btnPurchase))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2)
                    .addComponent(jLabel4)
                    .addComponent(txtPP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn3)
                    .addComponent(jLabel6)
                    .addComponent(txtRP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtRP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4)
                    .addComponent(jLabel8)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn5)
                    .addComponent(jLabel9)
                    .addComponent(cmbCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(cou < 4){
            int selectedRow = tblManageFunds.getSelectedRow();
        if (selectedRow >= 0) {
                FundProduct fp = (FundProduct) tblManageFunds.getValueAt(selectedRow, 0);
                list.add(fp);
                cou++;
        } else {
            JOptionPane.showMessageDialog(null, "Please select one row!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "There can only be 4 Fund Products in compare list at most!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCompareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompareActionPerformed
        // TODO add your handling code here:
        if(list.size() > 1){
            CompareJPanel cjp = new CompareJPanel(userProcessContainer, list);
        userProcessContainer.add("CompareJPanel", cjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please add at least 2 Fund Products to compare list!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        list.removeAll(list);
        cou = 0;
    }//GEN-LAST:event_btnCompareActionPerformed

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblManageFunds.getSelectedRow();
        if (selectedRow >= 0) {
                FundProduct fp = (FundProduct) tblManageFunds.getValueAt(selectedRow, 0);
                PurchaseJPanel ljp = new PurchaseJPanel(userProcessContainer, fp, account, enterprise, business);
                userProcessContainer.add("PurchaseJPanel", ljp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(null, "Please select one row!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPurchaseActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblManageFunds.getSelectedRow();
        if (selectedRow >= 0) {
                FundProduct fp = (FundProduct) tblManageFunds.getValueAt(selectedRow, 0);
                LookDetailsJPanel ljp = new LookDetailsJPanel(userProcessContainer, fp);
                userProcessContainer.add("LookDetailsJPanel", ljp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(null, "Please select one row!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtRP1.setText("");
        txtRP2.setText("");
        cmbType.setSelectedItem(null);
        cmbCompany.setSelectedItem(null);
        result = new ArrayList<>();
        if(Validation.IsLegalString(txtPP1.getText()) == true && Validation.IsLegalString(txtPP2.getText()) == true
                && Validation.IsDigit(txtPP1.getText()) == true && Validation.IsDigit(txtPP2.getText()) == true){
            for(FundProduct fp : allDirectory.getFundProductDirectory()){
            if(fp.getPurchasePrice() <= Double.parseDouble(txtPP2.getText()) && fp.getPurchasePrice()>= Double.parseDouble(txtPP1.getText())){
                result.add(fp);
            }
        }
        populateTable2();
        }
        else
        JOptionPane.showMessageDialog(null, "Please enter correct information!", "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        txtPP1.setText("");
        txtPP2.setText("");
        txtRP1.setText("");
        txtRP2.setText("");
        cmbCompany.setSelectedItem(null);
        cmbType.setSelectedItem(null);
        result = new ArrayList<>();
        for(FundProduct fp : allDirectory.getFundProductDirectory()){
            if(fp.getName().equals(txtName.getText())){
                result.add(fp);
            }
        }
        populateTable2();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtPP1.setText("");
        txtPP2.setText("");
        cmbCompany.setSelectedItem(null);
        cmbType.setSelectedItem(null);
        result = new ArrayList<>();
        if(Validation.IsLegalString(txtRP1.getText()) == true && Validation.IsLegalString(txtRP2.getText()) == true&& Validation.IsDigit(txtPP1.getText()) == true && Validation.IsDigit(txtPP2.getText()) == true){
            for(FundProduct fp : allDirectory.getFundProductDirectory()){
            if(fp.getPurchasePrice() <= Double.parseDouble(txtPP2.getText()) && fp.getPurchasePrice()>= Double.parseDouble(txtPP1.getText())){
                result.add(fp);
            }
        }
        populateTable2();
        }
        else
        JOptionPane.showMessageDialog(null, "Please enter correct information!", "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtPP1.setText("");
        txtPP2.setText("");
        txtRP1.setText("");
        txtRP2.setText("");
        cmbCompany.setSelectedItem(null);
        result = new ArrayList<>();
        for(FundProduct fp : allDirectory.getFundProductDirectory()){
            if(fp.getFundType().equals(cmbType.getSelectedItem())){
                result.add(fp);
            }
        }
        populateTable2();
    }//GEN-LAST:event_btn4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtPP1.setText("");
        txtPP2.setText("");
        txtRP1.setText("");
        txtRP2.setText("");
        cmbType.setSelectedItem(null);
        cmbCompany.setSelectedItem(null);
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtPP1.setText("");
        txtPP2.setText("");
        txtRP1.setText("");
        txtRP2.setText("");
        cmbType.setSelectedItem(null);
        result = new ArrayList<>();
        FundCompany fc = (FundCompany)cmbCompany.getSelectedItem();
        if(fc != null){
            for(FundProduct fp : fc.getFundProductDirectory().getFundProductDirectory()){
            result.add(fp);
        }
        populateTable2();
        }
        else
        JOptionPane.showMessageDialog(null, "Please select a Fund Company!", "Warning", JOptionPane.WARNING_MESSAGE);
        
    }//GEN-LAST:event_btn5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCompare;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JComboBox cmbCompany;
    private javax.swing.JComboBox cmbType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JTable tblManageFunds;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPP1;
    private javax.swing.JTextField txtPP2;
    private javax.swing.JTextField txtRP1;
    private javax.swing.JTextField txtRP2;
    // End of variables declaration//GEN-END:variables
}
