/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.PlatformTradeRole;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Enterprise.Bank;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Platform;
import Business.FundProduct.FundProduct;
import Business.Network.Network;
import Business.Organization.BankSavingsOrganization;
import Business.Organization.Organization;
import Business.TradeInformation.PurchaseTrade;
import Business.TradeInformation.Trade;
import Business.UserAccount.UserAccount;
import Interface.PlatformCustomerRole.PlatformCustomerWorkArea;
import Util.SendMail;
import java.awt.CardLayout;
import java.awt.Component;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author yangyun
 */
public class PurchaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PurchaseJPanel
     */
    JPanel userProcessContainer;
    FundProduct fp;
    UserAccount account;
    Platform enterprise;
    EcoSystem business;
    
    public PurchaseJPanel(JPanel userProcessContainer, FundProduct fp, UserAccount account, Platform enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.fp = fp;
        this.enterprise = enterprise;
        this.account = account;
        this.business = business;
        lblFund.setText(fp.getName());
        lblPrice.setText(String.valueOf(fp.getPurchasePrice()));
        lblTotal.setText("0.0");
        
        for(Customer c : enterprise.getCustomerdirectory()){
            cmbCustomer.addItem(c);
        }
        
        SpinnerNumberModel numModel = new SpinnerNumberModel(0, 0, 1000, 1);
        spnQuantity.setModel(numModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFund = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        btnPurchase = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbCustomer = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spnQuantity = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Purchase");

        jLabel2.setText("Fund Name:");

        jLabel3.setText("Purchase Price:");

        btnPurchase.setBackground(new java.awt.Color(255, 255, 255));
        btnPurchase.setText("Confirm Purchase");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Customer:");

        cmbCustomer.setBackground(new java.awt.Color(255, 255, 255));
        cmbCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCustomerActionPerformed(evt);
            }
        });

        jLabel5.setText("Customer ID: ");

        jLabel6.setText("Quantity:");

        spnQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnQuantityStateChanged(evt);
            }
        });

        jLabel7.setText("Total Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(119, 119, 119)
                .addComponent(btnPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFund, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCustomer, 0, 154, Short.MAX_VALUE)
                            .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblFund))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblPrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPurchase)
                    .addComponent(jButton3))
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] carray = userProcessContainer.getComponents();
        Component com = carray[carray.length - 1];
        PlatformTradeWorkArea panel = (PlatformTradeWorkArea) com;
        panel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        // TODO add your handling code here:
        PurchaseTrade trade = new PurchaseTrade(Trade.TradeType.Purchase);
        trade.setAmount(lblTotal.getText());
        trade.setSender(account);
        trade.setStatus("Send");
        trade.setCustomer((Customer) cmbCustomer.getSelectedItem());
        trade.setFp(fp);
        trade.setQuantity((int)spnQuantity.getValue());
        String quan = String.valueOf((int)spnQuantity.getValue());
        
        fp.setQuantity(fp.getQuantity() - (int)spnQuantity.getValue());
        fp.setSales(fp.getSales() + (int)spnQuantity.getValue());
        
        Customer cus = (Customer) cmbCustomer.getSelectedItem();
        cus.getTradeList().getTradeList().add(trade);
        
        Enterprise en = null;
        Organization org = null;
        
        for(Network net : business.getNetworkList()){
            for(Enterprise e : net.getEnterpriseDirectory().getEnterpriseList()){
                if(e == cus.getBank()){
                    en = e;
                    break;
                }
            }
        }
        
        if(en != null){
        for (Organization organization : en.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof BankSavingsOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getTradeDirectory().getTradeList().add(trade);
            account.getTradeDirectory().getTradeList().add(trade);
        }
        }
        //System.out.println(cus.getEmail());
        if(cus.getEmail() != null){
            try {
            
            SendMail.sendMessage("smtp.gmail.com", "highfivetradeplatform@gmail.com",  
                    "highfive123", cus.getEmail(), "Purchase Confirmation", 
                    "Dear " + cus.getName() +", you have purchased " + fp.getName() + " successfully. " + "Quantity: " + quan + ".",
                    "text/html;charset=gb2312");
            
            }catch(MessagingException e){
                //e.printStackTrace();
            }
        }
        
        JOptionPane.showMessageDialog(null, "Purchase successfully!", "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnPurchaseActionPerformed

    private void cmbCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCustomerActionPerformed
        // TODO add your handling code here:
        Customer cus = (Customer)cmbCustomer.getSelectedItem();
        lblID.setText(cus.getUserid());
    }//GEN-LAST:event_cmbCustomerActionPerformed

    private void spnQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnQuantityStateChanged
        // TODO add your handling code here:
        if((int)spnQuantity.getValue() <= fp.getQuantity()){
            double total = (int)spnQuantity.getValue() * fp.getPurchasePrice();
            lblTotal.setText(String.valueOf(total));
        }
        else{
            spnQuantity.setValue(fp.getQuantity());
            JOptionPane.showMessageDialog(null, "There are not enough Fund Products!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_spnQuantityStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPurchase;
    private javax.swing.JComboBox cmbCustomer;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblFund;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JSpinner spnQuantity;
    // End of variables declaration//GEN-END:variables
}
