/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.BankSavingsRole;

import Business.Customer.Customer;
import Business.Enterprise.Enterprise;
import Business.Organization.BankSavingsOrganization;
import Business.TradeInformation.PaymentTrade;
import Business.TradeInformation.Trade;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yangyun
 */
public class BankSavingsWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form BankSavingsWorkArea
     */
    JPanel userProcessContainer;
    UserAccount account;
    BankSavingsOrganization organization;
    Enterprise enterprise;
    
    public BankSavingsWorkArea(JPanel userProcessContainer, UserAccount account, BankSavingsOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tabTrade.getModel();
        
        model.setRowCount(0);
        
        for (Trade trade : organization.getTradeDirectory().getTradeList()){
            //if(trade.getReceiver().equals(account)){
                Object[] row = new Object[4];
                row[0] = trade;
                row[1] = trade.getTradeType();
                row[2] = trade.getStatus();
                row[3] = trade.getRequestDate();
                model.addRow(row);
            //}
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabTrade = new javax.swing.JTable();
        btnProcess = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("My Work Area - Bank Savings Role");

        tabTrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trade ID", "Trade Type", "Status", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabTrade);
        if (tabTrade.getColumnModel().getColumnCount() > 0) {
            tabTrade.getColumnModel().getColumn(0).setResizable(false);
            tabTrade.getColumnModel().getColumn(1).setResizable(false);
            tabTrade.getColumnModel().getColumn(2).setResizable(false);
            tabTrade.getColumnModel().getColumn(3).setResizable(false);
        }

        btnProcess.setBackground(new java.awt.Color(255, 255, 255));
        btnProcess.setText("Process Trade");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Trade");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProcess)
                .addGap(169, 169, 169))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnProcess))
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabTrade.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row.","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Trade trade = (Trade)tabTrade.getValueAt(selectedRow, 0);
        if(trade.getStatus().equals("Completed")){
            JOptionPane.showMessageDialog(null,"This Trade has been finished.","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
            trade.setStatus("Processing");
            ProcessTradeJPanel ProcessTradeJPanel = new ProcessTradeJPanel(userProcessContainer, trade);
            userProcessContainer.add("ProcessTradeJPanel", ProcessTradeJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabTrade.getSelectedRow();
        if(selectedRow >= 0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to Delete this Trade?","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                Trade t = (Trade)tabTrade.getValueAt(selectedRow, 0);
                organization.getTradeDirectory().deleteTrade(t);
                populateTable();
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select a row.","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnProcess;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabTrade;
    // End of variables declaration//GEN-END:variables
}
