/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Main;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author yangyun
 */
public class BlankJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BlankJPanel
     */
    private String PathPic = null;
    private ImageIcon imageicon = null;
    
    public BlankJPanel() {
        initComponents();
        setSize(800, 680);
        PathPic = "/Users/yangyun/davidyang/project/groupproject_highfive/FinalProject_HighFive/a2.png";
        imageicon = new ImageIcon(PathPic);
        imageicon.setImage(imageicon.getImage().getScaledInstance(800, 680, Image.SCALE_DEFAULT));
        lblShow2.setIcon(imageicon);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblShow2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblShow2, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblShow2, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblShow2;
    // End of variables declaration//GEN-END:variables
}
