/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.BankTradeRole;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Enterprise.Bank;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Platform;
import Business.Network.Network;
import Business.Organization.BankSavingsOrganization;
import Business.Organization.BankTradeOrganization;
import Business.Organization.Organization;
import Business.TradeInformation.PaymentTrade;
import Business.TradeInformation.Trade;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author yangyun
 */
public class BankTradeWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form BankTradeWorkArea
     */
    JPanel userProcessContainer;
    UserAccount account;
    BankTradeOrganization organization;
    Bank enterprise;
    EcoSystem business;
    
    public BankTradeWorkArea(JPanel userProcessContainer, UserAccount account, BankTradeOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = (Bank)enterprise;
        this.business = business;
        for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(o instanceof BankSavingsOrganization){
                for(UserAccount ua : o.getUserAccountDirectory().getUserAccountList()){
                    cmbReceiver.addItem(ua);
                }
            }
        }
        lblSender.setText(account.getUsername());
        
        for(Network n : business.getNetworkList()){
            for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof Platform){
                    Platform p = (Platform) e;
                    for(Customer c : p.getCustomerdirectory()){
                        if(c.getBank() == this.enterprise)
                        cmbCus.addItem(c);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lblSender = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        cmbReceiver = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cmbCus = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Make Deposit");

        jLabel3.setText("Sender:");

        jLabel4.setText("Receiver:");

        jLabel5.setText("Amount:");

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel6.setText("Customer:");

        cmbCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbReceiver, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAmount)
                                .addComponent(cmbCus, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSubmit))
                            .addComponent(lblSender, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSender, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        PaymentTrade trade = new PaymentTrade(Trade.TradeType.Deposit);
        trade.setAmount(Double.parseDouble(txtAmount.getText()));
        trade.setSender(account);
        trade.setReceiver((UserAccount)cmbReceiver.getSelectedItem());
        trade.setStatus("Send");
        trade.setTradeType(Trade.TradeType.Deposit);
        trade.setCustomer((Customer) cmbCus.getSelectedItem());

        Organization org = null;

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof BankSavingsOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getTradeDirectory().getTradeList().add(trade);
            account.getTradeDirectory().getTradeList().add(trade);
        }
        JOptionPane.showMessageDialog(null, "Deposit Trade sent successfully.", "Warning", JOptionPane.WARNING_MESSAGE);
        /*for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof BankSavingsOrganization){
                for(Trade t : organization.getTradeDirectory().getTradeList()){
                    System.out.println(t.getTradeID());
                }
            }
        }*/
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void cmbCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cmbCus;
    private javax.swing.JComboBox cmbReceiver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblSender;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables
}
